### ISSUE TITLE
kde plasma theme

### ISSUE THREAD

**Issue by mfat** [neeeeow/Bluecurve#10]
Is that possible?

**Comment by neeeeow** [comment]
Writing a KDE plasma theme is beyond the scope of this project.

Frankly, I have no experience in writing Qt themes, and I don't have the time to learn how - especially since I don't use KDE.

**Comment by jcontoso** [comment]
FYI, you can use GTK 2 themes with both Qt 5 and 6 using qt5-gtk2-platformtheme and qt6gtk2.

**Comment by ikkqqstudio** [comment]
> FYI, you can use GTK 2 themes with both Qt 5 and 6 using qt5-gtk2-platformtheme and qt6gtk2.

Oh, idk this existed
