### ISSUE TITLE
Can't fully maximize GTK4 applications. 

### ISSUE THREAD

**Issue by pablo-888** [neeeeow/Bluecurve#11]
Is that intentional? there is always (9px? 10px?) of empty space on all sides. GTK3 applications maximize just fine. 

![gtk4](https://github.com/user-attachments/assets/7680ec5f-d739-4188-9cc9-bca0af4698f4)
(made the wallpaper red to make it more clear.)

archlinux with GTK 4.14.5

**Comment by neeeeow** [comment]
This definitely should not be occurring.

What application are you using the screenshot? Just wondering as I do not have any GTK 4 programs with CSD's installed.

**Comment by neeeeow** [comment]
The margin should be set to 0 for when the window is maximised, but it should be 10px otherwise iirc. I probably messed something up when implementing the GTK 4 theme. I'll investigate this later when I have some time.

**Comment by neeeeow** [comment]
You were correct in that setting the margin to 0px in the GTK 4 CSD's resolves the issue. I also took the time to fix the CSDs of windows with compositing disabled in GTK 4.

This has been resolved in commit [3f9432f](https://github.com/neeeeow/Bluecurve/commit/3f9432f5f4c24cc954c6fa89f98e80a5df4c7c90) and this patch will be included in the next release.

Thanks for reporting this!
