### ISSUE TITLE
Open File dialog text alignment

### ISSUE THREAD

**Issue by sighook** [neeeeow/Bluecurve#14]
The GTK2 and GTK3 themes have different text alignment in Open File dialog.
For example (the gaps are marked with red):
![GTK2](https://github.com/user-attachments/assets/2d00c621-c6f3-43e7-b30e-26461c3a907f)
![GTK3](https://github.com/user-attachments/assets/963dabcb-d09e-4a33-bd61-e26fa867c083)

Is it possible to make the GTK3's alignment the same as GTK2's?

**Comment by neeeeow** [comment]
I managed to adjust the padding of the sidebar icons in the open file dialog to match the GTK 2 theme in commit [5b588bb](https://github.com/neeeeow/Bluecurve/commit/5b588bb2bc2bba03b4319196665d2f1d3738e670). Unfortunately, it doesn't seem to be possible to adjust the padding of icons in the actual file chooser treeview itself, however. 

I've managed to make it resemble the GTK 2 as much as is possible with GTK 3/4, and as a result I'll close this issue now.

Thanks for reporting this!
