### ISSUE TITLE
(GTK4) filechooser's selected items look wrong.

### ISSUE THREAD

**Issue by pablo-888** [neeeeow/Bluecurve#15]
![1727554243](https://github.com/user-attachments/assets/f0c00494-8c1d-4910-8f61-438a07fc272f)

Sidebar items (places, etc) also have black text when selected (I assume it's supposed to be white?). I tried looking at the CSS files but I couldn't figure it out myself this time 😁.

**Comment by neeeeow** [comment]
I'll investigate this when I have some time. There are quite a few bugs in the GTK 4 theme, arising from (frankly) very bizarre changes made by the gnome developers. It should be possible to resolve this.

**Comment by neeeeow** [comment]
I have finally gotten around to fixing this issue. See commit [bdd1a86](https://github.com/neeeeow/Bluecurve/commit/bdd1a86d510695e30ab19777233c75baab6d8dac).
