### ISSUE TITLE
Issues displaying frames compared to other themes

### ISSUE THREAD

**Issue by Azkuzku** [neeeeow/Bluecurve#16]
I'm using the theme on Mate, but I recall seeing this issue pop up in XFCE too. What i'm talking about is the frames getting cut off from the top, as if they have no spacing

Here is an example from the PCSX2 GS config
![GTKissue1](https://github.com/user-attachments/assets/d52c001f-f802-4651-9c32-675c1971f1a8)

Here it is using the default Mate theme
![GTKissue2](https://github.com/user-attachments/assets/00e09914-b5e9-408a-a49d-e5e719f57ef1)

**Comment by neeeeow** [comment]
Thanks for bringing this up. I had a few minutes spare and I resolved the issue. See commit [eced669](https://github.com/neeeeow/Bluecurve/commit/eced6693989abdcf473a12786319a507ddef60af).

**Comment by Azkuzku** [comment]
That's amazing! Thanks a lot. This is my favourite theme ever.
