### ISSUE TITLE
Theme makes firefox-esr tab bar hard to read

### ISSUE THREAD

**Issue by Azkuzku** [neeeeow/Bluecurve#17]
![image](https://github.com/user-attachments/assets/8c6eabf7-8d12-4c53-9d56-17925b241a17)
it's pretty self explanatory, the non-active colour is set way too bright

**Comment by neeeeow** [comment]
The issue has now been resolved. See commit [29f6ad9](https://github.com/neeeeow/Bluecurve/commit/29f6ad9ee182acb5b83471d83a58c0e74c27c67b).
