### ISSUE TITLE
Box outline around Brisk Menu icon

### ISSUE THREAD

**Issue by vyvir** [neeeeow/Bluecurve#2]
Steps to reproduce:

1. Install MATE
2. Install Brisk Menu
3. Put the Brisk Menu on panel
4. Apply Bluecurve theme 

![image](https://github.com/user-attachments/assets/a7063fc6-269f-4749-8c99-f7c66cb59d36)

**Comment by vyvir** [comment]
This box outline happens to all icons and doesn't happen with other themes:
![image](https://github.com/user-attachments/assets/b36018f4-a407-4135-9d8f-990cc013178e)
![image](https://github.com/user-attachments/assets/0b210c5d-f1a9-4475-85fd-ed77d36e244c)

**Comment by vyvir** [comment]
This doesn't happen with Advanced MATE menu, but happens with Brisk menu

**Comment by neeeeow** [comment]
Hmm, that's bizarre. I imagine Brisk Menu uses some weird CSS class for it's buttons that isn't included in the theme. Thanks for bringing this up. I'll investigate it over the weekend when I have time to fire up an openSUSE VM (sadly Brisk Menu isn't available in the Fedora repos).

**Comment by neeeeow** [comment]
I have discovered the issue, for some reason the brisk menu button uses it's own class. I'm working on implementing a fix (as well as adding some other tweaks to brisk menu's style in the theme). I'll close this issue once I commit the changes.

**Comment by neeeeow** [comment]
Issue has been fixed in commit [bf1f7df](https://github.com/neeeeow/Bluecurve/commit/bf1f7dfe93f6d82f96c2c7256996954dba119a97).

Thanks for reporting this!
