### ISSUE TITLE
Screen is greyed out when trying to take screen shot in XFCE

### ISSUE THREAD

**Issue by bunnymnemonic** [neeeeow/Bluecurve#3]
There is a glitch that does not happen with other themes: when I try to take a screenshot with xfce4-screenshoter (I choose the "select area" option), the whole screen becomes grey and I cannot see anything.

**Comment by bunnymnemonic** [comment]
Thank you very much for your quick answer and fixing this! It is interesting that deleting ".dialog-vbox" does not solve the problem for me. However, if I change the transparency of popup windows in Settings > Window manager settings > Compositing, the desktop becomes visible when using xfce4-screenshoter.

**Comment by neeeeow** [comment]
Yes sorry, I've just noticed I accidentally committed an incomplete fix, I'll commit the correct fix in a few minutes.

**Comment by neeeeow** [comment]
OK, now the issue has been resolved in commit [9fca9f2](https://github.com/neeeeow/Bluecurve/commit/9fca9f2466a34070676d4be3a8789bb631c0bf2f). I'll close the issue now, thanks for making me aware of this!

**Comment by bunnymnemonic** [comment]
Thank you very much!
