### ISSUE TITLE
MATE screenshot tool selection area is opaque

### ISSUE THREAD

**Issue by sillius-soddus** [neeeeow/Bluecurve#4]
My goodness, this is so good, no other Bluecurve theme that I have seen aside from original comes close to this (no offense to others). This is one of the best themes that I have seen. Thank you so much for creating this and sharing it with us.

I have to report an issue though, I am running Fedora 40 MATE spin, and when using MATE's default screenshot tool when I make a selection it's opaque, cannot see what I am selecting.

Once again, thank you.

**Comment by neeeeow** [comment]
Thanks for your lovely words! I think it's also important to give credits to the developers from which I created this.

I have resolved the issue in commit [5ad1b71](https://github.com/neeeeow/Bluecurve/commit/5ad1b71402c960d8a634a8cc938e346b7092af17).

Thanks for reporting this!
