### ISSUE TITLE
NixOS support

### ISSUE THREAD

**Issue by SpectralPixel** [neeeeow/Bluecurve#5]
I know this may be a lot to ask for, but could you package the theme for it to be compatible with NixOS Home-Manager? This would allow me to declaratively set up the theme, essentially making it automatically configure itself every time that I install NixOS on a new machine (this scenario is very likely for me).

As I'm new to NixOS myself I'm not exactly sure how to pull this off, but here are a few links that might point you in the correct direction:
- https://www.reddit.com/r/NixOS/comments/15s584d/how_to_change_gtk_theme
- https://nix-community.github.io/home-manager/options.xhtml#opt-gtk.enable
- https://search.nixos.org/packages?channel=unstable&query=gtk-theme

**Comment by neeeeow** [comment]
Sorry, I have never used NixOS before, and packaging this theme for NixOS is beyond the scope of the project. You're more than welcome to do it yourself, however.
