### ISSUE TITLE
Add dark themes

### ISSUE THREAD

**Issue by sudospaes** [neeeeow/Bluecurve#7]
They are awesome themes, if it is possible please add dark mode to them

**Comment by neeeeow** [comment]
I'm not sure how well a dark theme would work. I have some spare time so I'll try to see if it looks good; if it does I'll commit a dark theme to the repo.

**Comment by neeeeow** [comment]
Unfortunately dark colors do not work well with the GTK 2 engine, and thus it would be pointless implementing them in GTK 3/4.

**Comment by sudospaes** [comment]
> Unfortunately dark colors do not work well with the GTK 2 engine, and thus it would be pointless implementing them in GTK 3/4.

Not problem, thank you so much
