### ISSUE TITLE
Add a CMakeLists flag for global engine installation

### ISSUE THREAD

**Issue by vyvir** [neeeeow/Bluecurve#9]
I don't know how to ask this, but the source provide for the GTK2 engine automatically installs the engine to ~/.gtk2.0
While sufficient for a local install, this creates an obstacle for packaging. I created a patch that changed the directory to a root one, but it would be nice to have a flag or something, so that the script would choose a local/root directory based on the flag provided.

**Comment by vyvir** [comment]
The specific root directory is `${CMAKE_INSTALL_LIBDIR}/gtk-2.0/2.10.0/engines` I think

**Comment by neeeeow** [comment]
I imagine it's possible to add a flag to CMakeLists for a global install. I'll try and see what I can do.

**Comment by neeeeow** [comment]
The CMakeLists has been updated to allow the GTK 2 engine to be installed system-wide.

**Instructions for compiling & installing the GTK 2 engine system-wide**
```bash
cd engine/src
mkdir build && cd build
cmake -DINSTALL_SYSTEM_WIDE=ON ..
make
sudo make install
```
